// Async events
typedef enum
{
    WLC_E_NONE                           =  -1,
    WLC_E_SET_SSID                       =   0  /** indicates status of set SSID */,
    WLC_E_JOIN                           =   1, /** differentiates join IBSS from found (WLC_E_START) IBSS */
    WLC_E_START                          =   2, /** STA founded an IBSS or AP started a BSS */
    WLC_E_AUTH                           =   3, /** 802.11 AUTH request */
    WLC_E_AUTH_IND                       =   4, /** 802.11 AUTH indication */
    WLC_E_DEAUTH                         =   5, /** 802.11 DEAUTH request */
    WLC_E_DEAUTH_IND                     =   6, /** 802.11 DEAUTH indication */
    WLC_E_ASSOC                          =   7, /** 802.11 ASSOC request */
    WLC_E_ASSOC_IND                      =   8, /** 802.11 ASSOC indication */
    WLC_E_REASSOC                        =   9, /** 802.11 REASSOC request */
    WLC_E_REASSOC_IND                    =  10, /** 802.11 REASSOC indication */
    WLC_E_DISASSOC                       =  11, /** 802.11 DISASSOC request */
    WLC_E_DISASSOC_IND                   =  12, /** 802.11 DISASSOC indication */
    WLC_E_QUIET_START                    =  13, /** 802.11h Quiet period started */
    WLC_E_QUIET_END                      =  14, /** 802.11h Quiet period ended */
    WLC_E_BEACON_RX                      =  15, /** BEACONS received/lost indication */
    WLC_E_LINK                           =  16, /** generic link indication */
    WLC_E_MIC_ERROR                      =  17, /** TKIP MIC error occurred */
    WLC_E_NDIS_LINK                      =  18, /** NDIS style link indication */
    WLC_E_ROAM                           =  19, /** roam attempt occurred: indicate status & reason */
    WLC_E_TXFAIL                         =  20, /** change in dot11FailedCount (txfail) */
    WLC_E_PMKID_CACHE                    =  21, /** WPA2 pmkid cache indication */
    WLC_E_RETROGRADE_TSF                 =  22, /** current AP's TSF value went backward */
    WLC_E_PRUNE                          =  23, /** AP was pruned from join list for reason */
    WLC_E_AUTOAUTH                       =  24, /** report AutoAuth table entry match for join attempt */
    WLC_E_EAPOL_MSG                      =  25, /** Event encapsulating an EAPOL message */
    WLC_E_SCAN_COMPLETE                  =  26, /** Scan results are ready or scan was aborted */
    WLC_E_ADDTS_IND                      =  27, /** indicate to host addts fail/success */
    WLC_E_DELTS_IND                      =  28, /** indicate to host delts fail/success */
    WLC_E_BCNSENT_IND                    =  29, /** indicate to host of beacon transmit */
    WLC_E_BCNRX_MSG                      =  30, /** Send the received beacon up to the host */
    WLC_E_BCNLOST_MSG                    =  31, /** indicate to host loss of beacon */
    WLC_E_ROAM_PREP                      =  32, /** before attempting to roam */
    WLC_E_PFN_NET_FOUND                  =  33, /** PFN network found event */
    WLC_E_PFN_NET_LOST                   =  34, /** PFN network lost event */
    WLC_E_RESET_COMPLETE                 =  35,
    WLC_E_JOIN_START                     =  36,
    WLC_E_ROAM_START                     =  37,
    WLC_E_ASSOC_START                    =  38,
    WLC_E_IBSS_ASSOC                     =  39,
    WLC_E_RADIO                          =  40,
    WLC_E_PSM_WATCHDOG                   =  41, /** PSM microcode watchdog fired */
    WLC_E_CCX_ASSOC_START                =  42, /** CCX association start */
    WLC_E_CCX_ASSOC_ABORT                =  43, /** CCX association abort */
    WLC_E_PROBREQ_MSG                    =  44, /** probe request received */
    WLC_E_SCAN_CONFIRM_IND               =  45,
    WLC_E_PSK_SUP                        =  46, /** WPA Handshake */
    WLC_E_COUNTRY_CODE_CHANGED           =  47,
    WLC_E_EXCEEDED_MEDIUM_TIME           =  48, /** WMMAC excedded medium time */
    WLC_E_ICV_ERROR                      =  49, /** WEP ICV error occurred */
    WLC_E_UNICAST_DECODE_ERROR           =  50, /** Unsupported unicast encrypted frame */
    WLC_E_MULTICAST_DECODE_ERROR         =  51, /** Unsupported multicast encrypted frame */
    WLC_E_TRACE                          =  52,
    WLC_E_BTA_HCI_EVENT                  =  53, /** BT-AMP HCI event */
    WLC_E_IF                             =  54, /** I/F change (for wlan host notification) */
    WLC_E_P2P_DISC_LISTEN_COMPLETE       =  55, /** P2P Discovery listen state expires */
    WLC_E_RSSI                           =  56, /** indicate RSSI change based on configured levels */
    WLC_E_PFN_BEST_BATCHING              =  57, /** PFN best network batching event */
    WLC_E_EXTLOG_MSG                     =  58,
    WLC_E_ACTION_FRAME                   =  59, /** Action frame reception */
    WLC_E_ACTION_FRAME_COMPLETE          =  60, /** Action frame Tx complete */
    WLC_E_PRE_ASSOC_IND                  =  61, /** assoc request received */
    WLC_E_PRE_REASSOC_IND                =  62, /** re-assoc request received */
    WLC_E_CHANNEL_ADOPTED                =  63, /** channel adopted (xxx: obsoleted) */
    WLC_E_AP_STARTED                     =  64, /** AP started */
    WLC_E_DFS_AP_STOP                    =  65, /** AP stopped due to DFS */
    WLC_E_DFS_AP_RESUME                  =  66, /** AP resumed due to DFS */
    WLC_E_WAI_STA_EVENT                  =  67, /** WAI stations event */
    WLC_E_WAI_MSG                        =  68, /** event encapsulating an WAI message */
    WLC_E_ESCAN_RESULT                   =  69, /** escan result event */
    WLC_E_ACTION_FRAME_OFF_CHAN_COMPLETE =  70, /** action frame off channel complete */  /* NOTE - This used to be WLC_E_WAKE_EVENT */
    WLC_E_PROBRESP_MSG                   =  71, /** probe response received */
    WLC_E_P2P_PROBREQ_MSG                =  72, /** P2P Probe request received */
    WLC_E_DCS_REQUEST                    =  73,
    WLC_E_FIFO_CREDIT_MAP                =  74, /** credits for D11 FIFOs. [AC0,AC1,AC2,AC3,BC_MC,ATIM] */
    WLC_E_ACTION_FRAME_RX                =  75, /** Received action frame event WITH wl_event_rx_frame_data_t header */
    WLC_E_WAKE_EVENT                     =  76, /** Wake Event timer fired, used for wake WLAN test mode */
    WLC_E_RM_COMPLETE                    =  77, /** Radio measurement complete */
    WLC_E_HTSFSYNC                       =  78, /** Synchronize TSF with the host */
    WLC_E_OVERLAY_REQ                    =  79, /** request an overlay IOCTL/iovar from the host */
    WLC_E_CSA_COMPLETE_IND               =  80,
    WLC_E_EXCESS_PM_WAKE_EVENT           =  81, /** excess PM Wake Event to inform host  */
    WLC_E_PFN_SCAN_NONE                  =  82, /** no PFN networks around */
    WLC_E_PFN_SCAN_ALLGONE               =  83, /** last found PFN network gets lost */
    WLC_E_GTK_PLUMBED                    =  84,
    WLC_E_ASSOC_IND_NDIS                 =  85, /** 802.11 ASSOC indication for NDIS only */
    WLC_E_REASSOC_IND_NDIS               =  86, /** 802.11 REASSOC indication for NDIS only */
    WLC_E_ASSOC_REQ_IE                   =  87,
    WLC_E_ASSOC_RESP_IE                  =  88,
    WLC_E_ASSOC_RECREATED                =  89, /** association recreated on resume */
    WLC_E_ACTION_FRAME_RX_NDIS           =  90, /** rx action frame event for NDIS only */
    WLC_E_AUTH_REQ                       =  91, /** authentication request received */
    WLC_E_TDLS_PEER_EVENT                =  92, /** discovered peer, connected/disconnected peer */
    WLC_E_MESH_DHCP_SUCCESS              =  92, /** DHCP handshake successful for a mesh interface */
    WLC_E_SPEEDY_RECREATE_FAIL           =  93, /** fast assoc recreation failed */
    WLC_E_NATIVE                         =  94, /** port-specific event and payload (e.g. NDIS) */
    WLC_E_PKTDELAY_IND                   =  95, /** event for tx pkt delay suddently jump */
    WLC_E_AWDL_AW                        =  96, /** AWDL AW period starts */
    WLC_E_AWDL_ROLE                      =  97, /** AWDL Master/Slave/NE master role event */
    WLC_E_AWDL_EVENT                     =  98, /** Generic AWDL event */
    WLC_E_NIC_AF_TXS                     =  99, /** NIC AF txstatus */
    WLC_E_NAN                            = 100, /** NAN event */
    WLC_E_BEACON_FRAME_RX                = 101,
    WLC_E_SERVICE_FOUND                  = 102, /** desired service found */
    WLC_E_GAS_FRAGMENT_RX                = 103, /** GAS fragment received */
    WLC_E_GAS_COMPLETE                   = 104, /** GAS sessions all complete */
    WLC_E_P2PO_ADD_DEVICE                = 105, /** New device found by p2p offload */
    WLC_E_P2PO_DEL_DEVICE                = 106, /** device has been removed by p2p offload */
    WLC_E_WNM_STA_SLEEP                  = 107, /** WNM event to notify STA enter sleep mode */
    WLC_E_TXFAIL_THRESH                  = 108, /** Indication of MAC tx failures (exhaustion of 802.11 retries) exceeding threshold(s) */
    WLC_E_PROXD                          = 109, /** Proximity Detection event */
    WLC_E_IBSS_COALESCE                  = 110, /** IBSS Coalescing */
    WLC_E_MESH_PAIRED                    = 110, /** Mesh peer found and paired */
    WLC_E_AWDL_RX_PRB_RESP               = 111, /** AWDL RX Probe response */
    WLC_E_AWDL_RX_ACT_FRAME              = 112, /** AWDL RX Action Frames */
    WLC_E_AWDL_WOWL_NULLPKT              = 113, /** AWDL Wowl nulls */
    WLC_E_AWDL_PHYCAL_STATUS             = 114, /** AWDL Phycal status */
    WLC_E_AWDL_OOB_AF_STATUS             = 115, /** AWDL OOB AF status */
    WLC_E_AWDL_SCAN_STATUS               = 116, /** Interleaved Scan status */
    WLC_E_AWDL_AW_START                  = 117, /** AWDL AW Start */
    WLC_E_AWDL_AW_END                    = 118, /** AWDL AW End */
    WLC_E_AWDL_AW_EXT                    = 119, /** AWDL AW Extensions */
    WLC_E_AWDL_PEER_CACHE_CONTROL        = 120,
    WLC_E_CSA_START_IND                  = 121,
    WLC_E_CSA_DONE_IND                   = 122,
    WLC_E_CSA_FAILURE_IND                = 123,
    WLC_E_CCA_CHAN_QUAL                  = 124, /** CCA based channel quality report */
    WLC_E_BSSID                          = 125, /** to report change in BSSID while roaming */
    WLC_E_TX_STAT_ERROR                  = 126, /** tx error indication */
    WLC_E_BCMC_CREDIT_SUPPORT            = 127, /** credit check for BCMC supported */
    WLC_E_PSTA_PRIMARY_INTF_IND          = 128, /** psta primary interface indication */
    WLC_E_BT_WIFI_HANDOVER_REQ           = 130, /* Handover Request Initiated */
    WLC_E_SPW_TXINHIBIT                  = 131, /* Southpaw TxInhibit notification */
    WLC_E_FBT_AUTH_REQ_IND               = 132, /* FBT Authentication Request Indication */
    WLC_E_RSSI_LQM                       = 133, /* Enhancement addition for WLC_E_RSSI */
    WLC_E_PFN_GSCAN_FULL_RESULT          = 134, /* Full probe/beacon (IEs etc) results */
    WLC_E_PFN_SWC                        = 135, /* Significant change in rssi of bssids being tracked */
    WLC_E_AUTHORIZED                     = 136, /* a STA been authroized for traffic */
    WLC_E_PROBREQ_MSG_RX                 = 137, /* probe req with wl_event_rx_frame_data_t header */
    WLC_E_PFN_SCAN_COMPLETE              = 138, /* PFN completed scan of network list */
    WLC_E_RMC_EVENT                      = 139, /* RMC Event */
    WLC_E_DPSTA_INTF_IND                 = 140, /* DPSTA interface indication */
    WLC_E_RRM                            = 141, /* RRM Event */
    WLC_E_ULP                            = 146, /* ULP entry event */
    WLC_E_LAST                           = 147, /** highest val + 1 for range checking */
    WLC_E_FORCE_32_BIT                   = 0x7FFFFFFE  /** Force enum to be stored in 32 bit variable */
} wwd_event_num_t;
